import os
import uuid
import sqlite3
import json
from datetime import datetime, timezone

from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    storage_uri="memory://",
)

DB_PATH = "audit_log.db"
groq_client = Groq(api_key=os.environ["GROQ_API_KEY"])

DETECTION_SYSTEM_PROMPT = """You are an AI content provenance classifier for a creative writing platform. \
Determine whether the submitted text was written by a human or generated by an AI system.

Analyze for these AI-generation markers:
- Overly uniform sentence length and rhythm
- Formal hedging phrases ("it's important to note", "in conclusion", "furthermore", "notably")
- Absence of personal voice, idiosyncratic phrasing, or stylistic quirks
- Predictable logical structure with no unexpected tangents or digressions
- Broad but safe vocabulary — avoids slang, regional expressions, emotional rawness
- Flawless grammar with no intentional stylistic choices or natural speech patterns

Return ONLY valid JSON with exactly these fields:
{
  "attribution": "ai" | "human" | "uncertain",
  "confidence": <number 0.0 to 1.0>,
  "reasoning": "<one sentence>"
}

Guidelines:
- Use "uncertain" when evidence is mixed or the text is too short to classify confidently
- Only assign confidence above 0.85 when the signal is clear and strong
- Lean toward "uncertain" when unsure"""


# ── Database ──────────────────────────────────────────────────────────────────

def init_db():
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS submissions (
                content_id      TEXT PRIMARY KEY,
                creator_id      TEXT,
                timestamp       TEXT,
                content_preview TEXT,
                attribution     TEXT,
                confidence      REAL,
                label           TEXT,
                status          TEXT DEFAULT 'classified'
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS appeals (
                appeal_id         TEXT PRIMARY KEY,
                content_id        TEXT,
                creator_reasoning TEXT,
                status            TEXT DEFAULT 'under_review',
                timestamp         TEXT,
                FOREIGN KEY (content_id) REFERENCES submissions(content_id)
            )
        """)


# ── Detection ─────────────────────────────────────────────────────────────────

def classify_text(text):
    """Signal 1: LLM stylometric analysis via Groq."""
    response = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": DETECTION_SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        temperature=0,
        response_format={"type": "json_object"},
    )
    return json.loads(response.choices[0].message.content)


def attribution_to_label(attribution, confidence):
    if attribution == "ai" and confidence >= 0.85:
        return "High-confidence AI-generated"
    elif attribution == "human" and confidence >= 0.85:
        return "High-confidence human-written"
    return "Uncertain — provenance unclear"


# ── Routes ────────────────────────────────────────────────────────────────────

@app.route("/")
def home():
    return "Provenance Guard is running."


@app.route("/submit", methods=["POST"])
@limiter.limit("1 per second")
def submit():
    data = request.get_json()
    if not data or not data.get("text"):
        return jsonify({"error": "text field is required"}), 400

    text = data["text"]
    creator_id = data.get("creator_id", "anonymous")
    content_id = str(uuid.uuid4())

    detection = classify_text(text)
    attribution = detection.get("attribution", "uncertain")
    confidence = float(detection.get("confidence", 0.5))
    label = attribution_to_label(attribution, confidence)

    with sqlite3.connect(DB_PATH) as conn:
        conn.execute(
            "INSERT INTO submissions VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            (
                content_id,
                creator_id,
                datetime.now(timezone.utc).isoformat(),
                text[:200],
                attribution,
                confidence,
                label,
                "classified",
            ),
        )

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()
    if not data or not data.get("content_id") or not data.get("creator_reasoning"):
        return jsonify({"error": "content_id and creator_reasoning are required"}), 400

    content_id = data["content_id"]
    reasoning = data["creator_reasoning"]

    with sqlite3.connect(DB_PATH) as conn:
        row = conn.execute(
            "SELECT content_id FROM submissions WHERE content_id = ?", (content_id,)
        ).fetchone()
        if not row:
            return jsonify({"error": "content_id not found"}), 404

        appeal_id = str(uuid.uuid4())
        conn.execute(
            "INSERT INTO appeals VALUES (?, ?, ?, ?, ?)",
            (
                appeal_id,
                content_id,
                reasoning,
                "under_review",
                datetime.now(timezone.utc).isoformat(),
            ),
        )
        conn.execute(
            "UPDATE submissions SET status = 'under_review' WHERE content_id = ?",
            (content_id,),
        )

    return jsonify({
        "appeal_id": appeal_id,
        "content_id": content_id,
        "status": "under_review",
        "message": "Your appeal was received and is under review.",
    })


@app.route("/log", methods=["GET"])
def get_log():
    limit = request.args.get("limit", 20, type=int)
    with sqlite3.connect(DB_PATH) as conn:
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            "SELECT * FROM submissions ORDER BY timestamp DESC LIMIT ?", (limit,)
        ).fetchall()
    return jsonify([dict(row) for row in rows])


# ── Startup ───────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    init_db()
    app.run(port=5000, debug=True)
