import os
import re
import uuid
import sqlite3
import json
import statistics
from datetime import datetime, timezone

from flask import Flask, request, jsonify, render_template_string
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    storage_uri="memory://",
)

DB_PATH = "audit_log.db"
groq_client = Groq(api_key=os.environ["GROQ_API_KEY"])

DETECTION_SYSTEM_PROMPT = """You are an AI content provenance classifier for a creative writing platform. \
Determine whether the submitted text was written by a human or generated by an AI system.

Analyze for these AI-generation markers:
- Overly uniform sentence length and rhythm
- Formal hedging phrases ("it's important to note", "in conclusion", "furthermore", "notably")
- Absence of personal voice, idiosyncratic phrasing, or stylistic quirks
- Predictable logical structure with no unexpected tangents or digressions
- Broad but safe vocabulary — avoids slang, regional expressions, emotional rawness
- Flawless grammar with no intentional stylistic choices or natural speech patterns

Return ONLY valid JSON with exactly these fields:
{
  "attribution": "ai" | "human" | "uncertain",
  "confidence": <number 0.0 to 1.0>,
  "reasoning": "<one sentence>"
}

Guidelines:
- Use "uncertain" when evidence is mixed or the text is too short to classify confidently
- Only assign confidence above 0.85 when the signal is clear and strong
- Lean toward "uncertain" when unsure"""

# Formal transition phrases that appear more frequently in AI-generated writing
TRANSITION_PHRASES = {
    "however", "moreover", "furthermore", "in conclusion", "notably",
    "in addition", "consequently", "therefore", "additionally",
    "it is important to note", "it is worth noting", "in summary",
    "to summarize", "as a result", "on the other hand", "with that said",
    "in contrast", "for instance", "in this regard", "to elaborate",
}


# ── Database ──────────────────────────────────────────────────────────────────

def init_db():
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS submissions (
                content_id      TEXT PRIMARY KEY,
                creator_id      TEXT,
                timestamp       TEXT,
                content_preview TEXT,
                attribution     TEXT,
                confidence      REAL,
                label           TEXT,
                status          TEXT DEFAULT 'classified'
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS appeals (
                appeal_id         TEXT PRIMARY KEY,
                content_id        TEXT,
                creator_reasoning TEXT,
                status            TEXT DEFAULT 'under_review',
                timestamp         TEXT,
                FOREIGN KEY (content_id) REFERENCES submissions(content_id)
            )
        """)


# ── Detection ─────────────────────────────────────────────────────────────────

def classify_text(text):
    """Signal 1: LLM stylometric analysis via Groq."""
    response = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": DETECTION_SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        temperature=0,
        response_format={"type": "json_object"},
    )
    return json.loads(response.choices[0].message.content)


def stylometric_score(text):
    """Signal 2: Stylometric heuristics. Returns 0.0 (human-like) to 1.0 (AI-like).

    Three metrics:
      1. Sentence-length CV   — low variance = uniform = AI signal
      2. Transition density   — formal connectors per sentence = AI signal
      3. Punctuation variety  — fewer distinct marks relative to total = AI signal
    """
    sentences = [s.strip() for s in re.split(r'(?<=[.!?])\s+', text.strip()) if s.strip()]

    # Metric 1: coefficient of variation of sentence word-lengths
    # CV = stdev / mean; low CV → uniform rhythm → AI
    if len(sentences) >= 3:
        lengths = [len(s.split()) for s in sentences]
        mean_len = statistics.mean(lengths)
        cv = statistics.stdev(lengths) / mean_len if mean_len > 0 else 0
        # CV 0.0 → score 1.0 (pure uniformity); CV ≥ 1.0 → score 0.0 (high variance)
        cv_score = max(0.0, min(1.0, 1.0 - cv))
    else:
        cv_score = 0.5  # not enough sentences to judge

    # Metric 2: transition phrase density per sentence
    text_lower = text.lower()
    hits = sum(1 for phrase in TRANSITION_PHRASES if phrase in text_lower)
    density = hits / max(len(sentences), 1)
    # 0 transitions → 0.0; ≥0.5 per sentence → 1.0
    transition_score = min(1.0, density * 2.0)

    # Metric 3: punctuation variety (inverted — diversity signals human authorship)
    punct_chars = re.findall(r'[.,!?;:\'"–—…]', text)
    if punct_chars:
        variety_ratio = len(set(punct_chars)) / len(punct_chars)
        # High variety (≥0.5) → human → low AI score; low variety → AI
        punct_score = max(0.0, min(1.0, 1.0 - variety_ratio * 1.5))
    else:
        punct_score = 0.5

    return round((cv_score + transition_score + punct_score) / 3, 4)


def combine_signals(signal1_result, signal2_score):
    """Merge Signal 1 (LLM) and Signal 2 (stylometric) into a single verdict.

    Both signals are normalised to a 0–1 AI-likelihood scale before combining.
    Weights: Signal 1 = 70% (semantic context), Signal 2 = 30% (surface heuristics).

    Threshold verification against planning.md spec:
      combined ≥ 0.85  → attribution "ai",    confidence ≥ 0.85 → "High-confidence AI-generated"
      combined ≤ 0.15  → attribution "human", confidence ≥ 0.85 → "High-confidence human-written"
      everything else  →                                           "Uncertain — provenance unclear"
    """
    s1_attribution = signal1_result.get("attribution", "uncertain")
    s1_confidence  = float(signal1_result.get("confidence", 0.5))

    # Convert Signal 1 to a 0–1 directional score (higher = more AI-like)
    if s1_attribution == "ai":
        s1_score = s1_confidence
    elif s1_attribution == "human":
        s1_score = 1.0 - s1_confidence
    else:
        s1_score = 0.5

    combined = round(0.70 * s1_score + 0.30 * signal2_score, 4)

    # Attribution bands
    if combined >= 0.60:
        attribution = "ai"
    elif combined <= 0.40:
        attribution = "human"
    else:
        attribution = "uncertain"

    # Confidence = certainty in whichever direction we lean
    # (symmetric: 0.90 combined → 0.90 confidence for AI; 0.10 combined → 0.90 for human)
    confidence = round(max(combined, 1.0 - combined), 4)

    return {
        "attribution": attribution,
        "confidence": confidence,
        "label": attribution_to_label(attribution, confidence),
        "signal1_score": round(s1_score, 4),
        "signal2_score": round(signal2_score, 4),
    }


def attribution_to_label(attribution, confidence):
    if attribution == "ai" and confidence >= 0.85:
        return "High-confidence AI-generated"
    elif attribution == "human" and confidence >= 0.85:
        return "High-confidence human-written"
    return "Uncertain — provenance unclear"


# ── Routes ────────────────────────────────────────────────────────────────────

HOME_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Provenance Guard</title>
  <style>
    body { font-family: sans-serif; max-width: 680px; margin: 60px auto; padding: 0 16px; color: #222; }
    h1 { font-size: 1.4rem; margin-bottom: 4px; }
    p.sub { color: #666; margin-top: 0; font-size: 0.9rem; }
    label { display: block; font-weight: 600; margin: 16px 0 4px; }
    input[type=text], textarea {
      width: 100%; box-sizing: border-box; padding: 8px;
      border: 1px solid #ccc; border-radius: 4px; font-size: 0.95rem;
    }
    textarea { height: 160px; resize: vertical; }
    button {
      margin-top: 12px; padding: 10px 24px; background: #2563eb;
      color: #fff; border: none; border-radius: 4px; cursor: pointer; font-size: 0.95rem;
    }
    button:disabled { background: #93c5fd; cursor: not-allowed; }
    #result { margin-top: 24px; padding: 16px; border-radius: 6px; display: none; }
    #result.ai      { background: #fef2f2; border: 1px solid #fca5a5; }
    #result.human   { background: #f0fdf4; border: 1px solid #86efac; }
    #result.uncertain { background: #fffbeb; border: 1px solid #fcd34d; }
    .label { font-size: 1.05rem; font-weight: 700; margin-bottom: 8px; }
    .meta  { font-size: 0.85rem; color: #555; }
    .error { background: #fef2f2; border: 1px solid #fca5a5; color: #991b1b; }
  </style>
</head>
<body>
  <h1>Provenance Guard</h1>
  <p class="sub">Submit text to classify its provenance — human-written or AI-generated.</p>

  <label for="creator_id">Creator ID</label>
  <input type="text" id="creator_id" placeholder="e.g. user-123" value="test-user-1">

  <label for="text">Content</label>
  <textarea id="text" placeholder="Paste the text you want to classify..."></textarea>

  <button id="btn" onclick="submitContent()">Analyze</button>

  <div id="result"></div>

  <script>
    async function submitContent() {
      const text = document.getElementById("text").value.trim();
      const creator_id = document.getElementById("creator_id").value.trim() || "anonymous";
      const btn = document.getElementById("btn");
      const result = document.getElementById("result");

      if (!text) { alert("Please enter some text first."); return; }

      btn.disabled = true;
      btn.textContent = "Analyzing…";
      result.style.display = "none";

      try {
        const res = await fetch("/submit", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ text, creator_id }),
        });
        const data = await res.json();

        if (!res.ok) {
          result.className = "error";
          result.innerHTML = `<strong>Error:</strong> ${data.error}`;
        } else {
          const cls = data.attribution === "ai" ? "ai"
                    : data.attribution === "human" ? "human" : "uncertain";
          result.className = cls;
          result.innerHTML = `
            <div class="label">${data.label}</div>
            <div class="meta">
              Attribution: <strong>${data.attribution}</strong> &nbsp;|&nbsp;
              Confidence: <strong>${(data.confidence * 100).toFixed(1)}%</strong><br>
              Signal 1 (LLM): <strong>${(data.signal1_score * 100).toFixed(1)}%</strong> &nbsp;|&nbsp;
              Signal 2 (stylometric): <strong>${(data.signal2_score * 100).toFixed(1)}%</strong><br>
              Content ID: <code>${data.content_id}</code>
            </div>`;
        }
        result.style.display = "block";
      } catch (e) {
        result.className = "error";
        result.innerHTML = "<strong>Network error.</strong> Is the server running?";
        result.style.display = "block";
      } finally {
        btn.disabled = false;
        btn.textContent = "Analyze";
      }
    }
  </script>
</body>
</html>"""


@app.route("/")
def home():
    return render_template_string(HOME_HTML)


@app.route("/submit", methods=["POST"])
@limiter.limit("1 per second")
def submit():
    data = request.get_json()
    if not data or not data.get("text"):
        return jsonify({"error": "text field is required"}), 400

    text = data["text"]
    creator_id = data.get("creator_id", "anonymous")
    content_id = str(uuid.uuid4())

    signal1 = classify_text(text)
    signal2 = stylometric_score(text)
    result  = combine_signals(signal1, signal2)

    with sqlite3.connect(DB_PATH) as conn:
        conn.execute(
            "INSERT INTO submissions VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            (
                content_id,
                creator_id,
                datetime.now(timezone.utc).isoformat(),
                text[:200],
                result["attribution"],
                result["confidence"],
                result["label"],
                "classified",
            ),
        )

    return jsonify({
        "content_id":    content_id,
        "attribution":   result["attribution"],
        "confidence":    result["confidence"],
        "label":         result["label"],
        "signal1_score": result["signal1_score"],
        "signal2_score": result["signal2_score"],
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()
    if not data or not data.get("content_id") or not data.get("creator_reasoning"):
        return jsonify({"error": "content_id and creator_reasoning are required"}), 400

    content_id = data["content_id"]
    reasoning = data["creator_reasoning"]

    with sqlite3.connect(DB_PATH) as conn:
        row = conn.execute(
            "SELECT content_id FROM submissions WHERE content_id = ?", (content_id,)
        ).fetchone()
        if not row:
            return jsonify({"error": "content_id not found"}), 404

        appeal_id = str(uuid.uuid4())
        conn.execute(
            "INSERT INTO appeals VALUES (?, ?, ?, ?, ?)",
            (
                appeal_id,
                content_id,
                reasoning,
                "under_review",
                datetime.now(timezone.utc).isoformat(),
            ),
        )
        conn.execute(
            "UPDATE submissions SET status = 'under_review' WHERE content_id = ?",
            (content_id,),
        )

    return jsonify({
        "appeal_id": appeal_id,
        "content_id": content_id,
        "status": "under_review",
        "message": "Your appeal was received and is under review.",
    })


@app.route("/log", methods=["GET"])
def get_log():
    limit = request.args.get("limit", 20, type=int)
    with sqlite3.connect(DB_PATH) as conn:
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            "SELECT * FROM submissions ORDER BY timestamp DESC LIMIT ?", (limit,)
        ).fetchall()
    return jsonify([dict(row) for row in rows])


# ── Startup ───────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    init_db()
    app.run(port=5000, debug=True)
